/* This file is automagically generated by build. Do NOT edit. */

#define VERSION_BUILD  203
#define VERSION_USER   "lundman"
#define VERSION_HOST   "shinken.local"
#define VERSION_DATE   "Sun Mar 24 16:46:01 2019"
#define VERSION_STRING "lundman@shinken.local build 203 (Sun Mar 24 16:46:01 2019)"

/* Lundtastic services */
